-- 코드를 입력하세요
SELECT A.AUTHOR_ID
     , A.AUTHOR_NAME
     , B.CATEGORY
     , SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
  FROM AUTHOR A
     , BOOK B
     , BOOK_SALES BS
 WHERE 1 = 1
   AND A.AUTHOR_ID = B.AUTHOR_ID
   AND B.BOOK_ID = BS.BOOK_ID
   AND TO_CHAR(BS.SALES_DATE, 'YYYYMM') = '202201'
 GROUP BY A.AUTHOR_ID
     , A.AUTHOR_NAME
     , B.CATEGORY
 ORDER BY A.AUTHOR_ID
     , B.CATEGORY DESC